<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models;
use App\Http\Requests;
use App\Column;
use Auth;
use Validator;
use Route;
use DB;

class ColumnController extends Controller
{
    /**
     * protected Variable.
     */
    protected $auth;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        global $models, $column;

        $models = new Models();
        $column = new Column();

        //Valodating User Session
        $this->middleware('auth');

        $this->middleware(function ($request, $next) {

            $this->session = Auth::user();
            parent::__construct($this->session);

            //Checking current request is allowed or not
            $allowedAction = array('index', 'navigation');
            $actionData    = explode('@', Route::currentRouteAction());
            $action        = !empty($actionData[1]) ? trim(strtolower($actionData[1])) : '0';
            if (defined('NOTALlOWEDTONAVIGATE') && empty(NOTALlOWEDTONAVIGATE) && in_array($action, $allowedAction)) {
                return redirect('dashboard')->withErrors('Permission Denied!');
            }
            return $next($request);
        });
    }

    /*********************************
     * Display a listing of the resource.
     * Date : 29-Nov-2021
     * Author : Praveen Singh
     *********************************/
    public function index()
    {
        global $models, $column;

        $user_id            = defined('USERID') ? USERID : '0';
        $division_id        = defined('DIVISIONID') ? DIVISIONID : '0';
        $department_ids     = defined('DEPARTMENT_IDS') ? DEPARTMENT_IDS : '0';
        $role_ids           = defined('ROLE_IDS') ? ROLE_IDS : '0';
        $equipment_type_ids = defined('EQUIPMENT_TYPE_IDS') ? EQUIPMENT_TYPE_IDS : '0';

        return view('master.column_master.index', ['title' => 'Column Master', '_column_master' => 'active', 'user_id' => $user_id, 'division_id' => $division_id, 'equipment_type_ids' => $equipment_type_ids]);
    }

    /*********************************
     * Auto Generate Code
     * Date : 29-Nov-2021
     * Author : Praveen Singh
     *********************************/
    public function getAutoGeneratedCode()
    {
        global $models, $column;

        $prefix = !empty(config('messages.message.columnPrefix')) ? config('messages.message.columnPrefix') : 'D';
        $code   = $models->generateCode($prefix, 'column_master', 'column_code', 'column_id');   //prefix,tableName,fieldName,primaryKey

        return response()->json(['uniqueCode' => $code]);
    }

    /*********************************
     * Laist All Columns
     * Date : 29-Nov-2021
     * Author : Praveen Singh
     *********************************/
    public function listMasters()
    {
        global $models;

        $masterDataObj = DB::table('column_master')
            ->join('equipment_type', 'column_master.equipment_type_id', 'equipment_type.equipment_id')
            ->join('product_categories', 'product_categories.p_category_id', 'column_master.product_category_id')
            ->join('users', 'column_master.created_by', 'users.id')
            ->select('column_master.*', 'equipment_type.equipment_name', 'product_categories.p_category_name', 'users.name as createdBy');

        if (!empty($equipment_type_id)) {
            $masterDataObj->where('column_master.equipment_type_id', '=', $equipment_type_id);
        }
        $masterDataList = $masterDataObj->orderBy('column_master.column_id', 'DESC')->get()->toArray();

        //Format Timestamps
        $models->formatTimeStampFromArray($masterDataList, DATETIMEFORMAT);

        return response()->json(['masterDataList' => $masterDataList]);
    }

    /*********************************
     * create New Column
     * Date : 29-Nov-2021
     * Author : Praveen Singh
     *********************************/
    public function createMaster(Request $request)
    {
        global $models, $column;

        $error    = '0';
        $message  = config('messages.message.error');
        $data    = $formData = array();

        try {
            if (!empty($request->formData) && $request->isMethod('post')) {

                //pasrse searlize data 
                parse_str($request->formData, $formData);

                if (empty($formData['column_code'])) {
                    $message = config('messages.message.required');
                } else if (empty($formData['column_name'])) {
                    $message = config('messages.message.required');
                } else if (empty($formData['column_desc'])) {
                    $message = config('messages.message.required');
                } else if (empty($formData['equipment_type_id'])) {
                    $message = config('messages.message.required');
                } else if (empty($formData['product_category_id'])) {
                    $message = config('messages.message.required');
                } elseif (!empty($column->where('column_code', $formData['column_code'])->count())) {
                    $message = config('messages.message.existError');
                } else {

                    //Unsetting the variable from request data
                    $formData = $models->unsetFormDataVariables($formData, array('_token'));

                    //Saving the data in customer_gst_categories Master
                    $formData['created_by'] = USERID;
                    $column_id = DB::table('column_master')->insertGetId($formData);

                    //check if users created add data in user detail
                    if ($column_id) {
                        $error    = '1';
                        $message = config('messages.message.success');
                    } else {
                        $message = config('messages.message.savedError');
                    }
                }
            } else {
                $message = config('messages.message.dataNotFoundToSaved');
            }
        } catch (\Illuminate\Database\QueryException $ex) {
            $message = config('messages.message.error');
        }
        return response()->json(['error' => $error, 'message' => $message]);
    }

    /*********************************
     * Edit Particular Column
     * Date : 29-Nov-2021
     * Author : Praveen Singh
     *********************************/
    public function editMaster($id)
    {
        global $models, $column;

        $error    = '0';
        $message  = config('messages.message.error');
        $data    = $formData = array();

        if ($id) {
            $data  = DB::table('column_master')->where('column_master.column_id', '=', $id)->first();
            $error = '1';
            $message  = '';
            if (empty($data)) {
                $error    = '0';
                $message = config('messages.message.noRecordFound');
            }
        } else {
            $message = config('messages.message.provideAppData');
        }
        return response()->json(['error' => $error, 'message' => $message, 'editMasterData' => $data]);
    }

    /*********************************
     * Update the specified resource in storage.
     * Date : 29-Nov-2021
     * Author : Praveen Singh
     *********************************/
    public function updateMaster(Request $request)
    {
        global $models, $column;

        $error    = '0';
        $message  = config('messages.message.error');
        $data    = $formData = array();

        try {

            if (!empty($request->formData) && $request->isMethod('post')) {

                //pasrse searlize data 
                parse_str($request->formData, $formData);

                if (empty($formData['column_id'])) {
                    $message  = config('messages.message.dataNotFound');
                } else if (empty($formData['column_name'])) {
                    $message = config('messages.message.required');
                } else if (empty($formData['column_desc'])) {
                    $message = config('messages.message.required');
                } else if (empty($formData['equipment_type_id'])) {
                    $message = config('messages.message.required');
                } else if (empty($formData['product_category_id'])) {
                    $message = config('messages.message.required');
                } else {
                    $updated = DB::table('column_master')->where('column_id', $formData['column_id'])->update([
                        'column_desc'             => $formData['column_desc'],
                        'column_name'             => $formData['column_name'],
                        'equipment_type_id'       => $formData['equipment_type_id'],
                        'product_category_id'     => $formData['product_category_id']
                    ]);
                    if ($updated) {
                        $error    = '1';
                        $message = config('messages.message.updated');
                    } else {
                        $error    = '1';
                        $message = config('messages.message.savedNoChange');
                    }
                }
            } else {
                $message = config('messages.message.dataNotFound');
            }
        } catch (\Illuminate\Database\QueryException $ex) {
            $message = config('messages.message.error');
        }
        return response()->json(['error' => $error, 'message' => $message]);
    }

    /*********************************
     * Delete the specified resource in storage.
     * Date : 29-Nov-2021
     * Author : Praveen Singh
     *********************************/
    public function destroyMaster(Request $request, $id)
    {
        global $models, $column;

        $error    = '0';
        $message  = config('messages.message.error');
        $data    = $formData = array();

        try {
            if ($id) {
                $column = DB::table('column_master')->where('column_id', $id)->delete();
                if ($column) {
                    $error    = '1';
                    $message = config('messages.message.deleted');
                } else {
                    $message = config('messages.message.deletedError');
                }
            }
        } catch (\Illuminate\Database\QueryException $ex) {
            $message = config('messages.message.foreignKeyDeleteError');
        }
        return response()->json(['error' => $error, 'message' => $message]);
    }
}
