<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models;
use App\Http\Requests;
use Auth;
use App\State;
use Validator;
use Route;
use DB;

class HoldController extends Controller
{
	/**
	 * protected Variable.
	 */
	protected $auth;
	
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        global $models;
		$models = new Models();
		$this->middleware('auth'); 
		$this->middleware(function ($request, $next) {
            $this->session = Auth::user();
			parent::__construct($this->session);
			//Checking current request is allowed or not
			$allowedAction = array('index','navigation');
			$actionData    = explode('@',Route::currentRouteAction());
			$action        = !empty($actionData[1]) ? trim(strtolower($actionData[1])): '0';			
			if(defined('NOTALlOWEDTONAVIGATE') && empty(NOTALlOWEDTONAVIGATE) && in_array($action,$allowedAction)){
				return redirect('dashboard')->withErrors('Permission Denied!');
			}
            return $next($request);
		 });
    }	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
		  $user_id            = defined('USERID') ? USERID : '0';
		  $division_id   	    = defined('DIVISIONID') ? DIVISIONID : '0';		
		  $department_ids     = defined('DEPARTMENT_IDS') ? DEPARTMENT_IDS : '0';
		  $role_ids           = defined('ROLE_IDS') ? ROLE_IDS : '0';		
		  $equipment_type_ids = defined('EQUIPMENT_TYPE_IDS') ? EQUIPMENT_TYPE_IDS : '0';
		
		return view('master.hold_master.index',['title' => 'Hold List','_holdList' => 'active']);
    }
	 /**
     * Function to generate code( autogenerate )
	  * created_by : Ruby
	  * created_on : 27-12-2018
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
	 public function getAutoGeneratedCode(Request $request) {
	     global $models;
		  $prefix=!empty(config('messages.message.holdPrefix')) ? config('messages.message.holdPrefix') : 'HLD';
		  $code=$models->generateCode_v1($prefix,'order_hold_master','oh_code','oh_id');
		  return response()->json(['uniqueCode' =>$code]);		
	 }
	 
    /** save amendment record
    *  Show the form for creating a new resource.
    * created_by : Ruby
	 * created_on : 27-12-2018
    * @return \Illuminate\Http\Response
    */
    public function create(Request $request){
	
	$returnData = array();
	
	$error    = '0';
	$message  = config('messages.message.error');
	$data     = '';
	
	if($request->isMethod('post') && !empty($request['data']['formData'])){
	
	    //pasrse searlize data 
	    $newPostData = array();
	    
	    parse_str($request['data']['formData'], $newPostData);
	    unset($newPostData['_token']);
	    
		 
	    if(empty($newPostData['oh_name'])){
		$returnData = array('error' => config('messages.message.holdtNameRequired'));
	    }else if(empty($newPostData['oh_code'])){
		$returnData = array('error' => config('messages.message.holdCodeRequired'));
	    }else if(isset($newPostData['oh_status']) && $newPostData['oh_status'] == ''){
		$returnData = array('error' => config('messages.message.holdStatusRequired'));
	    }else{		
		  try{
				//Adding New Dynamic Fields
				$formData['oh_name']   = ucwords(strtolower($newPostData['oh_name']));
				$formData['oh_code']   = $newPostData['oh_code'];
				$formData['oh_status'] = $newPostData['oh_status'];
				//echo'<pre>$formData'; print_r($formData); echo'</pre>';die;
				if(!empty($formData['oh_name'])){
				$save = DB::table('order_hold_master')->insertGetId($formData);	
					 if(!empty($save)){
						  $error   = '1';
						  $data    = $save;
						  $message = config('messages.message.saved');                                    
					 }
				}
		  }catch(\Illuminate\Database\QueryException $ex){
		    $message = config('messages.message.exist');
		  }
	    }	
	}else{
	    $message  = config('messages.message.error');
	}
	
	return response()->json(array('error'=> $error,'message'=> $message,'data'=> $data));	
    }

	 /**
	 * Get list of amendments on page load.
	 * created_by : Ruby
	 * created_on : 27-12-2018
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
    public function getHoldList(){
		 
		global $models;
		$holdsList = DB::table('order_hold_master')->orderBy('order_hold_master.oh_code','DESC')->get();
		//echo'<pre>'; print_r($holdsList);  die('come');
		$models->formatTimeStampFromArray($holdsList,DATETIMEFORMAT);
		return response()->json(['holdsList' => $holdsList,]);
    }   
   
    /**
     * Show the form for editing the specified resource.
     * created_by : Ruby
	  * created_on : 27-12-2018
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {
		$returnData = array();
		if ($request->isMethod('post')) {
			if(!empty($request['data']['id'])){
				$amendData = DB::table('order_hold_master')
								->where('order_hold_master.oh_id', '=', $request['data']['id'])
								->first();
				
				if($amendData->oh_id){
					$returnData = array('responseData' => $amendData);				
				}else{
					$returnData = array('error' => config('messages.message.noRecordFound'));
				}
			}else{
				$returnData = array('error' => config('messages.message.dataNotFoundToSaved'));
			}
		}else{
				$returnData = array('error' => config('messages.message.provideAppData'));			
		}
		return response()->json($returnData);	
    }
    /**
     * Update the specified resource in storage.
     * created_by : Ruby
	  * created_on : 27-12-2018
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request){
    
		  $returnData = array();
		  if ($request->isMethod('post')) {
				if(!empty($request['data']['formData'])){   
					//pasrse searlize data 
					 $newPostData = array();
					 parse_str($request['data']['formData'], $newPostData);
					 //echo'<pre>'; print_r($newPostData); die;
					 if(empty($newPostData['oh_name'])){
						  $returnData = array('error' => config('messages.message.holdNameRequired'));
					 }else if(empty($newPostData['oh_code'])){
						  $returnData = array('error' => config('messages.message.holdCodeRequired'));
					 }else if(isset($newPostData['oh_status']) && $newPostData['oh_status'] == ''){
						  $returnData = array('error' => config('messages.message.holdStatusRequired'));
					 }else{
						  try{
						  $updated = DB::table('order_hold_master')->where('order_hold_master.oh_id',$newPostData['oh_id'])->update([
								'oh_status' 	=> $newPostData['oh_status'],
								'oh_code' 		=> $newPostData['oh_code'],
								'oh_name' 		=> ucwords($newPostData['oh_name']),
						  ]);
						
						  if(!empty($updated)){
								 $returnData = array('success' => config('messages.message.holdUpdated'));  
							}else{
								$returnData = array('success' => config('messages.message.savedNoChange'));   
							}
						  }catch(\Illuminate\Database\QueryException $ex){
								$returnData = array('error' => config('messages.message.exist')); 
						  }
					 }
				}else{
					$returnData = array('error' =>  config('messages.message.dataNotFound'));
				}
		  }else{
			  $returnData = array('error' => config('messages.message.dataNotFound'));
		  } 
		  return response()->json($returnData);
    }

    /**
     * Remove the specified resource from storage.
     * created_by : Ruby
	  * created_on : 27-12-2018
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete(Request $request)
    {
		$returnData = array();
		if ($request->isMethod('post')){
			if(!empty($request['data']['id'])){
				try { 
					$holdData = DB::table('order_hold_master')->where('order_hold_master.oh_id', $request['data']['id'])->delete();
					if($holdData){
						$returnData = array('success' => config('messages.message.holdDeleted'));
					}else{
						$returnData = array('error' => config('messages.message.holdNotDeleted'));					
					}
				}catch(\Illuminate\Database\QueryException $ex){ 
				   $returnData = array('error' => config('messages.message.foreignKeyDeleteError'));
				}
			}else{
				$returnData = array('error' => config('messages.message.noRecordFound'));
			}
		}
		return response()->json($returnData);
    }
}
