<?php
/*****************************
*Created By  : Praveen Singh
*Created On  : 09-Nov-2019
*Modified On : 09-Nov-2019
******************************/

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\OrderReportDiscipline;
use App\Models;
use Auth;
use Session;
use Validator;
use Route;
use DB;

class OrderReportDisciplineController extends Controller
{
    /**
    * protected Variable.
    */
    protected $auth;
    
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct(){
	
        global $models,$orderReportDiscipline;
	
        $models = new Models();
	$orderReportDiscipline = new OrderReportDiscipline();
        
        //MiddleWare CHecking Loin Inn Authentication
        $this->middleware('auth');
	
        $this->middleware(function ($request, $next) {
            $this->auth = Auth::user();
	    parent::__construct($this->auth);
	    //Checking current request is allowed or not
	    $allowedAction = array('index','navigation');
	    $actionData    = explode('@',Route::currentRouteAction());
	    $action        = !empty($actionData[1]) ? trim(strtolower($actionData[1])): '0';			
	    if(defined('NOTALlOWEDTONAVIGATE') && empty(NOTALlOWEDTONAVIGATE) && in_array($action,$allowedAction)){
		return redirect('dashboard')->withErrors('Permission Denied!');
	    }
            return $next($request);
        });	
    }
	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
	
	global $models,$orderReportDiscipline;
	
	$user_id            = defined('USERID') ? USERID : '0';
	$division_id   	    = defined('DIVISIONID') ? DIVISIONID : '0';		
	$department_ids     = defined('DEPARTMENT_IDS') ? DEPARTMENT_IDS : '0';
	$role_ids           = defined('ROLE_IDS') ? ROLE_IDS : '0';		
	$equipment_type_ids = defined('EQUIPMENT_TYPE_IDS') ? EQUIPMENT_TYPE_IDS : '0';
		
        return view('master.discipline_master.index',['title' => 'Discipline Master','_discipline_master' => 'active','user_id' => $user_id,'division_id' => $division_id,'equipment_type_ids' => $equipment_type_ids]);
    }
    
     /**
     * Auto Generate code
     *
     * @return \Illuminate\Http\Response
     */
    public function getAutoGeneratedCode(Request $request){
        
        global $models,$orderReportDiscipline;
        
        $autoGenUniqueCode = $models->generateCode('DISP','order_report_disciplines','or_discipline_code','or_discipline_id');   //prefix,tableName,fieldName,primaryKey						  
        return response()->json(['uniqueCode' => $autoGenUniqueCode]);		
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function createMaster(Request $request){
	
        global $models,$orderReportDiscipline;
        
        $error    = '0';
        $message  = config('messages.message.error');
        $data     = '';
        $formData = array();
        $tableName = 'order_report_disciplines';
        
        //Saving record in table
        if(!empty($request->formData) && $request->isMethod('post')){                        
            
	    //Parsing the form Data
            parse_str($request->formData, $formData);
            //echo '<pre>';print_r($formData);die;
                                    
            if(!empty($formData)){                
                
                if(empty($formData['or_discipline_code'])){
                    $message = config('messages.message.required');
                }else if(empty($formData['or_discipline_name'])){
                    $message = config('messages.message.required');
                }else if(empty($formData['or_discipline_status'])){
                    $message = config('messages.message.required'); 
                }else if(!empty($formData['or_discipline_code']) && $orderReportDiscipline->validateCode($formData['or_discipline_code'])){  
                    $message = config('messages.message.existError');
                }else if(!empty($formData['or_discipline_name']) && $orderReportDiscipline->validateName($formData['or_discipline_name'])){  
                    $message = config('messages.message.existError');
                } else{
		    try{		    
			//Unsetting the variable from request data
			$formData = $models->unsetFormDataVariables($formData,array('_token'));
			$formData['or_discipline_created_by'] = USERID;                        
                        if(!empty(DB::table($tableName)->insertGetId($formData))){
                            $error   = '1';
                            $message = config('messages.message.saved');
                        }else{
                            $message = config('messages.message.savedError');    
                        }
		    }catch(\Illuminate\Database\QueryException $ex){
			$message = config('messages.message.existError');
		    }
		}                
            }
        }        
        return response()->json(array('error'=> $error,'message'=> $message,'data' => $data));	
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function listMasters(Request $request){
	
	global $models,$orderReportDiscipline;
	
	$error    = '0';
	$message  = config('messages.message.error');
	$data     = '';
	$formData = array();
	
	$masterDataList = DB::table('order_report_disciplines')
                    ->join('users','users.id','order_report_disciplines.or_discipline_created_by')
                    ->select('order_report_disciplines.*','users.name as or_discipline_created_name')
                    ->orderBy('order_report_disciplines.or_discipline_id','DESC')
                    ->get()
                    ->toArray();
                    
        $error    = !empty($masterDataList) ? '1' :  '0';
	$message  = !empty($error) ? '' :config('messages.message.error');

	//to formate created and updated date		   
	$models->formatTimeStampFromArray($masterDataList,DATETIMEFORMAT);
	
	return response()->json(array('error' => $error,'message' => $message,'masterDataList' => $masterDataList));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function viewMaster(Request $request,$id){
        
        global $models,$orderReportDiscipline;
	
	$error    = '0';
	$message  = config('messages.message.error');
	$data     = '';
	$formData = array();
        
        if($id){
            $masterDataList = DB::table('order_report_disciplines')
                    ->join('users','users.id','order_report_disciplines.or_discipline_created_by')
                    ->select('order_report_disciplines.*','users.name as or_discipline_created_name')
                    ->where('order_report_disciplines.or_discipline_id',$id)
                    ->orderBy('order_report_disciplines.or_discipline_id','DESC')
                    ->first();
                    
            $error    = !empty($masterDataList) ? 1 : '0';
            $message  = $error ? '' : $message;
        }	
	return response()->json(array('error' => $error,'message' => $message,'editMasterData' => $masterDataList));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function updateMaster(Request $request){
        
        global $models,$orderReportDiscipline;
        
        $error    = '0';
        $message  = config('messages.message.error');
        $data     = '';
        $formData = array();
        $tableName = 'order_report_disciplines';
        
        //Saving record in table
        if(!empty($request->formData) && $request->isMethod('post')){                        
            
	    //Parsing the form Data
            parse_str($request->formData, $formData);
            
            if(empty($formData['or_discipline_id'])){
                $message = config('messages.message.error');
            }else if(empty($formData['or_discipline_name'])){
                $message = config('messages.message.required');
            }else if(empty($formData['or_discipline_status'])){
                $message = config('messages.message.required'); 
            }else if(!empty($formData['or_discipline_code']) && $orderReportDiscipline->validateCode($formData['or_discipline_code'],$type='edit',$d=$formData['or_discipline_id'])){  
                $message = config('messages.message.existError');
            }else if(!empty($formData['or_discipline_name']) && $orderReportDiscipline->validateName($formData['or_discipline_name'],$type='edit',$d=$formData['or_discipline_id'])){  
                $message = config('messages.message.existError');
            } else{
                try{
                    //Getting Discipline ID
                    $or_discipline_id = !empty($formData['or_discipline_id']) ? $formData['or_discipline_id'] : '0';
                    
                    //Unsetting the variable from request data
                    $formData = $models->unsetFormDataVariables($formData,array('_token','or_discipline_id'));
                
                    if(!empty($or_discipline_id) && !empty($formData)){
                        if(DB::table($tableName)->where('or_discipline_id',$or_discipline_id)->update($formData)){
                            $error   = '1';
                            $message = config('messages.message.updated');    
                        }else{
                            $error   = '1';
                            $message = config('messages.message.savedNoChange');  
                        }
                    }else{
                        $message = config('messages.message.updatedError'); 
                    }
                }catch(\Illuminate\Database\QueryException $ex){
                    $message = config('messages.message.updatedError');
                }
            }
        }        
        return response()->json(array('error' => $error,'message' => $message,'data' => $data));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroyMaster($id){
        
        global $models,$orderReportDiscipline;
        
        $error   = '0';
        $message = '';
        $data    = '';
        $tableName = 'order_report_disciplines';
        
        try{
            if(DB::table($tableName)->where('or_discipline_id',$id)->delete()){
                $error   = '1';
                $message = config('messages.message.deleted');      
            }else{
                $message = config('messages.message.deletedError');
            }
        }catch(\Illuminate\Database\QueryException $ex){
            $message = config('messages.message.deletedError');
        }             
	return response()->json(['error' => $error,'message' => $message]);
    }
}
